title: (not so) secure apps
description: Ramblings of a cyber engineer
author: Ali Clarke
github: https://github.com/alijnclarke
about: I'm a cyber security engineer, specialising in mobile platforms.
disqus_shortname: secureapps-io
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/aliclarke_"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/agusmakmun
    - text: XML Feed
      url: /feed.xml

url: "https://alijnclarke.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
