title: alijnclarke.com
description: Ramblings of a cyber engineer
author: Ali Clarke
github: https://github.com/alijnclarke
about: I'm a cyber security engineer, specialising in mobile platforms.
disqus_shortname: alijnclarke-com
google_analytics: UA-87359410-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/aliclarke_"
    - icon: fa-linkedin
      link: "#"


share:
  twitter_username: aliclarke_
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/alijnclarke
    - text: XML Feed
      url: /feed.xml

url: "https://alijnclarke.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
